services:
  vllm_bge:
    image: vllm
    container_name: vllm_bge
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["vllm", "serve"]
    command:
      - BAAI/bge-large-en-v1.5
      - --tensor-parallel-size
      - "2"
      - --gpu-memory-utilization
      - "0.7"
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    volumes:
      - ./models:/models
    networks:
      - proxy
    environment:
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES} 
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      HF_HOME: /models
      HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
    runtime: nvidia
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.vllm_bge.entrypoints=websecure"
      - "traefik.http.routers.vllm_bge.rule=Host(`dominio.com.br`)"
      - "traefik.http.routers.vllm_bge.tls=true"
      - "traefik.http.services.vllm_bge.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
